# Generated by Django 4.2.30 on 2026-04-12 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('contador', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VersiculoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contador',
        ),
        migrations.RemoveField(
            model_name='versiculo',
            name='usado',
        ),
        migrations.AddField(
            model_name='versiculousado',
            name='versiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versiculos.versiculo'),
        ),
    ]
