services:
  - type: web
    name: moria-celula
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py popular_perguntas
      python manage.py collectstatic --noinput
    startCommand: daphne -b 0.0.0.0 -p $PORT moria.asgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
      - key: REDIS_URL
        fromService:
          name: moria-redis
          type: redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: moria-db
          property: connectionString

  - type: redis
    name: moria-redis
    plan: free

databases:
  - name: moria-db
    plan: free
