# Generated by Django 5.0.4 on 2026-04-17 19:09

import celula.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("texto", models.TextField(verbose_name="Texto")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Aviso",
                "verbose_name_plural": "Avisos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="PedidoOracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("pedido", models.TextField(verbose_name="Pedido")),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("respondido", "Respondido"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "testemunho",
                    models.TextField(blank=True, verbose_name="Testemunho / resposta"),
                ),
                ("anonimo", models.BooleanField(default=False, verbose_name="Anônimo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pedido de Oração",
                "verbose_name_plural": "Pedidos de Oração",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Reuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("data", models.DateTimeField(verbose_name="Data e hora")),
                (
                    "local",
                    models.CharField(blank=True, max_length=200, verbose_name="Local"),
                ),
                (
                    "link_online",
                    models.URLField(blank=True, verbose_name="Link online"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Reunião",
                "verbose_name_plural": "Reuniões",
                "ordering": ["data"],
            },
        ),
        migrations.CreateModel(
            name="SalaJogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        default=celula.models.gerar_codigo,
                        max_length=6,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando jogadores"),
                            ("em_jogo", "Em jogo"),
                            ("encerrada", "Encerrada"),
                        ],
                        default="aguardando",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pergunta_atual",
                    models.IntegerField(default=0, verbose_name="Pergunta atual"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sala de Jogo",
                "verbose_name_plural": "Salas de Jogo",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="TemaPergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Tema")),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tema",
                "verbose_name_plural": "Temas",
            },
        ),
        migrations.CreateModel(
            name="Versiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(max_length=100, verbose_name="Referência"),
                ),
                ("texto", models.TextField(verbose_name="Texto")),
                (
                    "ativo",
                    models.BooleanField(
                        default=True, verbose_name="Versículo da semana"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Versículo",
                "verbose_name_plural": "Versículos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Jogador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("pontos", models.IntegerField(default=0, verbose_name="Pontos")),
                ("channel_name", models.CharField(blank=True, max_length=200)),
                ("conectado", models.BooleanField(default=True)),
                ("entrou_em", models.DateTimeField(auto_now_add=True)),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogadores",
                        to="celula.salajogo",
                        verbose_name="Sala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jogador",
                "verbose_name_plural": "Jogadores",
                "ordering": ["-pontos"],
            },
        ),
        migrations.AddField(
            model_name="salajogo",
            name="tema",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="celula.temapergunta",
                verbose_name="Tema",
            ),
        ),
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz bíblico"),
                            ("reflexao", "Reflexão pessoal"),
                            ("desafio", "Verdade ou desafio"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("texto", models.TextField(verbose_name="Pergunta")),
                (
                    "versiculo",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Versículo de apoio"
                    ),
                ),
                ("reflexao", models.TextField(verbose_name="Reflexão para o grupo")),
                ("opcao_a", models.CharField(max_length=200, verbose_name="Opção A")),
                ("opcao_b", models.CharField(max_length=200, verbose_name="Opção B")),
                ("opcao_c", models.CharField(max_length=200, verbose_name="Opção C")),
                ("opcao_d", models.CharField(max_length=200, verbose_name="Opção D")),
                (
                    "resposta_correta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("", "Sem resposta certa"),
                        ],
                        max_length=1,
                        verbose_name="Resposta correta",
                    ),
                ),
                ("ativa", models.BooleanField(default=True)),
                (
                    "tema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perguntas",
                        to="celula.temapergunta",
                        verbose_name="Tema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pergunta",
                "verbose_name_plural": "Perguntas",
            },
        ),
        migrations.CreateModel(
            name="Resposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opcao_escolhida", models.CharField(max_length=1)),
                ("correta", models.BooleanField(default=False)),
                ("tempo_resposta", models.FloatField(default=0)),
                ("respondido_em", models.DateTimeField(auto_now_add=True)),
                (
                    "jogador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="celula.jogador",
                    ),
                ),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="celula.pergunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta",
                "verbose_name_plural": "Respostas",
                "unique_together": {("jogador", "pergunta")},
            },
        ),
    ]
