# Generated by Django 5.0.4 on 2026-04-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celula", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogador",
            name="is_lider",
            field=models.BooleanField(default=False),
        ),
    ]
