# Generated by Django 5.0.4 on 2026-04-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celula", "0002_jogador_is_lider"),
    ]

    operations = [
        migrations.AddField(
            model_name="pergunta",
            name="opcao_e",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Opção E"
            ),
        ),
        migrations.AlterField(
            model_name="pergunta",
            name="resposta_correta",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("", "Sem resposta certa"),
                ],
                max_length=1,
                verbose_name="Resposta correta",
            ),
        ),
    ]
